### ISSUE TITLE
 Desarrollo del Chat en Tiempo Real

### ISSUE THREAD

**Issue by BrandonCetina** [BrandonCetina/ChatBot#13]
Como equipo de desarrollo de la aplicación, queremos desarrollar la infraestructura para un sistema de chat en tiempo real, para que los usuarios puedan comunicarse instantáneamente con el chatbot y los agentes de soporte, sin demoras significativas en la entrega de mensajes.

- [ ] Seleccionar Tecnologías de Mensajería
- [ ] Desarrollar la Infraestructura de Mensajería
- [ ] Pruebas de Rendimiento
