### ISSUE TITLE
Diseño de la Interfaz de Usuario del Chat

### ISSUE THREAD

**Issue by BrandonCetina** [BrandonCetina/ChatBot#21]
Como equipo de diseño y desarrollo, queremos diseñar una interfaz de chat que sea intuitiva y accesible desde todas las secciones de la aplicación, para que los usuarios puedan interactuar fácilmente con el chatbot y los agentes humanos.

- [ ] Diseño de la Interfaz de Usuario
- [ ] Implementación de Funcionalidades
- [ ] Pruebas de Usabilidad

Criterios de Éxito:

Interfaz de chat fácil de usar en todos los dispositivos.
Funcionalidades como emojis y archivos adjuntos funcionan correctamente.
Feedback positivo de los usuarios sobre la usabilidad de la interfaz.
